# Generated by Django 4.2.5 on 2023-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, null=True, verbose_name="Nome"),
                ),
                ("descircao", models.TextField(verbose_name="Email")),
                (
                    "ativo",
                    models.BooleanField(blank=True, null=True, verbose_name="Ativo?"),
                ),
            ],
            options={"verbose_name": "Equipe", "verbose_name_plural": "1. Equipes",},
        ),
        migrations.DeleteModel(name="Gestor",),
    ]
