# Generated by Django 3.2 on 2023-10-05 12:05

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipe_delete_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome')),
                ('descircao', models.TextField(verbose_name='Email')),
                ('tipo_meta', models.SmallIntegerField(blank=True, choices=[(1, 'Colaborador'), (core.constants.EnumTipoMeta['EQUIPE'], 'Equipe')], null=True, verbose_name='Tipo de meta')),
                ('ativo', models.BooleanField(blank=True, null=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': '2. Metas',
            },
        ),
    ]
