# Generated by Django 3.2 on 2023-10-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='descircao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
