# Generated by Django 3.2 on 2023-10-05 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_equipe_gestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='descircao',
        ),
        migrations.AddField(
            model_name='equipe',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type_user': 2}, null=True, related_name='equipes', to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='gestor',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_user': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
