# Generated by Django 4.2.5 on 2023-11-12 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_rename_descircao_meta_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meta',
            options={'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AddField(
            model_name='meta',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='meta',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='meta',
            name='progresso_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Progresso Atual'),
        ),
        migrations.AddField(
            model_name='meta',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='meta',
            name='valor_alvo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Alvo'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type_user': 3}, null=True, related_name='colaboradores_meta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meta',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='equipe',
            field=models.ManyToManyField(blank=True, null=True, related_name='equipes_meta', to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='gestor',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_user': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestor_metas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meta',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='tipo_meta',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Colaborador'), (2, 'Equipe')], null=True, verbose_name='Tipo de meta'),
        ),
    ]
