# Generated by Django 4.2.5 on 2023-11-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_meta_options_meta_data_fim_meta_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='unidade_medida',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Unidades'), (2, 'Reais'), (3, 'Porcentagem'), (4, 'Horas'), (5, 'Dias'), (6, 'Projetos')], null=True, verbose_name='Unidade de Medida'),
        ),
    ]
