# Generated by Django 4.2.5 on 2023-11-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_meta_unidade_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='progresso_atual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Progresso Atual'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='valor_alvo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Valor Alvo'),
        ),
    ]
