# Generated by Django 4.2.5 on 2023-11-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_data_fim_meta_datafim_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meta',
            options={'verbose_name': '2. Meta', 'verbose_name_plural': '2. Metas'},
        ),
        migrations.CreateModel(
            name='AtualizarMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('valor_atualizacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Atualização')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='core.meta')),
            ],
        ),
    ]
