# Generated by Django 4.2.5 on 2023-11-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_meta_options_atualizarmeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atualizarmeta',
            options={'verbose_name': '3. Atualizar Meta', 'verbose_name_plural': '3. Atualizar Metas'},
        ),
        migrations.RenameField(
            model_name='atualizarmeta',
            old_name='valor_atualizacao',
            new_name='valorAtualizacao',
        ),
        migrations.AddField(
            model_name='atualizarmeta',
            name='criadoEm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
    ]
