# Generated by Django 3.2 on 2023-11-16 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_meta_metabatida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoRelatorio', models.SmallIntegerField(blank=True, choices=[(1, 'Colaborador'), (2, 'Equipe')], null=True, verbose_name='Tipo de relatorio')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de metas')),
                ('finalizadas', models.IntegerField(blank=True, null=True, verbose_name='Mentas concluidas')),
                ('emAberto', models.IntegerField(blank=True, null=True, verbose_name='Metas em aberto')),
                ('naoFinalizadas', models.IntegerField(blank=True, null=True, verbose_name='Metas não finalizadas')),
                ('taxaSucesso', models.IntegerField(blank=True, null=True, verbose_name='Taxa de sucesso')),
                ('notaFinal', models.SmallIntegerField(blank=True, choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E')], null=True, verbose_name='Nota final')),
                ('colaborador', models.ForeignKey(blank=True, limit_choices_to={'type_user': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipe', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': '4. Relatorio',
                'verbose_name_plural': '4. Relatorios',
            },
        ),
    ]
