# Generated by Django 3.2 on 2023-10-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='addres',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Endereço'),
        ),
    ]
