# Generated by Django 3.2.13 on 2023-10-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_auto_20231005_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_user',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Gestor'), (3, 'Colaborador')], null=True, verbose_name='Tipo de usuário'),
        ),
    ]
