# Generated by Django 3.2.13 on 2023-10-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_alter_userprofile_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='addres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço'),
        ),
    ]
